[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
    Content-Type = "image/webp"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
